name: Playwright + Cucumber CI/CD with Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CI: false   # Prevent warnings from breaking the build

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Install Dependencies
        run: npm ci

      - name: Install Browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber Tests
        run: npm run test
 

      # Step 4: Create .env file from GitHub Secrets
      - name: Create .env file
        run: |
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
          echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> .env

      # Step 5: Run tests
      - name: Run tests
        run: npm test -- --watchAll=false

      # Step 6: Build React app
      - name: Build React app
        run: npm run build

      # Step 7: Deploy to Firebase Hosting
      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only hosting --token "${{ secrets.REACT_APP_FIREBASE_API_KEY }}"
